#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    # Enable Chinese Layer
    vim_help_language = "cn"
    # Code Indentation
    default_indent = 4
    expand_tab = true # expand Tab into spaces

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = "chinese"

# Enable support for python
[[layers]]
name = "lang#python"


# Enalble support for C/C++
[[layers]]
name = "lang#c"
enable_clang_syntax_highlight = true


# Enable support for rust
[[layers]]
name = "lang#rust"
# for formatting rust coderust"
# Don't forget to run the following command
# rustup component add rls rust-analysis rust-src
[[layers]]
name = "lsp"
filetypes = [ "rust" ]
[layers.override_cmd]
rust=["rls"]

